package com.seckill.mapper;

import com.seckill.pojo.MiaoshaMessage;
import com.seckill.pojo.MiaoshaMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    long countByExample(MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int deleteByExample(MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int insert(MiaoshaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    List<MiaoshaMessage> selectByExampleWithBLOBs(MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    List<MiaoshaMessage> selectByExample(MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    MiaoshaMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiaoshaMessage record, @Param("example") MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MiaoshaMessage record, @Param("example") MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiaoshaMessage record, @Param("example") MiaoshaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MiaoshaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaMessage record);
}