package com.seckill.mapper;

import com.seckill.pojo.MiaoshaMessageUser;
import com.seckill.pojo.MiaoshaMessageUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaMessageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    long countByExample(MiaoshaMessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int deleteByExample(MiaoshaMessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int insert(MiaoshaMessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaMessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    List<MiaoshaMessageUser> selectByExample(MiaoshaMessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    MiaoshaMessageUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiaoshaMessageUser record, @Param("example") MiaoshaMessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiaoshaMessageUser record, @Param("example") MiaoshaMessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaMessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaMessageUser record);
}