package com.seckill.mapper;

import com.seckill.pojo.MiaoshaUser;
import com.seckill.pojo.MiaoshaUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    long countByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int deleteByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int insert(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    List<MiaoshaUser> selectByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    MiaoshaUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiaoshaUser record, @Param("example") MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiaoshaUser record, @Param("example") MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaUser record);
}