package com.seckill.mapper;

import com.seckill.pojo.MiaoshaOrder;
import com.seckill.pojo.MiaoshaOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    long countByExample(MiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int deleteByExample(MiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int insert(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    List<MiaoshaOrder> selectByExample(MiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    MiaoshaOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiaoshaOrder record, @Param("example") MiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiaoshaOrder record, @Param("example") MiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaOrder record);
}