package com.seckill.mapper;

import com.seckill.pojo.MiaoshaGoods;
import com.seckill.pojo.MiaoshaGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    long countByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    List<MiaoshaGoods> selectByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    MiaoshaGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiaoshaGoods record, @Param("example") MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiaoshaGoods record, @Param("example") MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaGoods record);
}