package com.seckill.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MiaoshaMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.MESSAGEID
     *
     * @mbg.generated
     */
    private Long messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.STATUS
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.OVER_TIME
     *
     * @mbg.generated
     */
    private Date overTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.MESSAGE_TYPE
     *
     * @mbg.generated
     */
    private Integer messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.SEND_TYPE
     *
     * @mbg.generated
     */
    private Integer sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.GOOD_NAME
     *
     * @mbg.generated
     */
    private String goodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.PRICE
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message._SLOT
     *
     * @mbg.generated
     */
    private String slot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.ID
     *
     * @return the value of miaosha_message.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.ID
     *
     * @param id the value for miaosha_message.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.MESSAGEID
     *
     * @return the value of miaosha_message.MESSAGEID
     *
     * @mbg.generated
     */
    public Long getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.MESSAGEID
     *
     * @param messageid the value for miaosha_message.MESSAGEID
     *
     * @mbg.generated
     */
    public void setMessageid(Long messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.CREATE_TIME
     *
     * @return the value of miaosha_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.CREATE_TIME
     *
     * @param createTime the value for miaosha_message.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.STATUS
     *
     * @return the value of miaosha_message.STATUS
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.STATUS
     *
     * @param status the value for miaosha_message.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.OVER_TIME
     *
     * @return the value of miaosha_message.OVER_TIME
     *
     * @mbg.generated
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.OVER_TIME
     *
     * @param overTime the value for miaosha_message.OVER_TIME
     *
     * @mbg.generated
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.MESSAGE_TYPE
     *
     * @return the value of miaosha_message.MESSAGE_TYPE
     *
     * @mbg.generated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.MESSAGE_TYPE
     *
     * @param messageType the value for miaosha_message.MESSAGE_TYPE
     *
     * @mbg.generated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.SEND_TYPE
     *
     * @return the value of miaosha_message.SEND_TYPE
     *
     * @mbg.generated
     */
    public Integer getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.SEND_TYPE
     *
     * @param sendType the value for miaosha_message.SEND_TYPE
     *
     * @mbg.generated
     */
    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.GOOD_NAME
     *
     * @return the value of miaosha_message.GOOD_NAME
     *
     * @mbg.generated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.GOOD_NAME
     *
     * @param goodName the value for miaosha_message.GOOD_NAME
     *
     * @mbg.generated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName == null ? null : goodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.PRICE
     *
     * @return the value of miaosha_message.PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.PRICE
     *
     * @param price the value for miaosha_message.PRICE
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message._SLOT
     *
     * @return the value of miaosha_message._SLOT
     *
     * @mbg.generated
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message._SLOT
     *
     * @param slot the value for miaosha_message._SLOT
     *
     * @mbg.generated
     */
    public void setSlot(String slot) {
        this.slot = slot == null ? null : slot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message.CONTENT
     *
     * @return the value of miaosha_message.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message.CONTENT
     *
     * @param content the value for miaosha_message.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", messageid=").append(messageid);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", overTime=").append(overTime);
        sb.append(", messageType=").append(messageType);
        sb.append(", sendType=").append(sendType);
        sb.append(", goodName=").append(goodName);
        sb.append(", price=").append(price);
        sb.append(", slot=").append(slot);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}