package com.seckill.pojo;

import java.io.Serializable;

public class MiaoshaMessageUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user.USERID
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user.MESSAGEID
     *
     * @mbg.generated
     */
    private Long messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user.GOODID
     *
     * @mbg.generated
     */
    private Integer goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user.ORDERID
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_message_user._SLOT
     *
     * @mbg.generated
     */
    private String slot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user.ID
     *
     * @return the value of miaosha_message_user.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user.ID
     *
     * @param id the value for miaosha_message_user.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user.USERID
     *
     * @return the value of miaosha_message_user.USERID
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user.USERID
     *
     * @param userid the value for miaosha_message_user.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user.MESSAGEID
     *
     * @return the value of miaosha_message_user.MESSAGEID
     *
     * @mbg.generated
     */
    public Long getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user.MESSAGEID
     *
     * @param messageid the value for miaosha_message_user.MESSAGEID
     *
     * @mbg.generated
     */
    public void setMessageid(Long messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user.GOODID
     *
     * @return the value of miaosha_message_user.GOODID
     *
     * @mbg.generated
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user.GOODID
     *
     * @param goodid the value for miaosha_message_user.GOODID
     *
     * @mbg.generated
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user.ORDERID
     *
     * @return the value of miaosha_message_user.ORDERID
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user.ORDERID
     *
     * @param orderid the value for miaosha_message_user.ORDERID
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_message_user._SLOT
     *
     * @return the value of miaosha_message_user._SLOT
     *
     * @mbg.generated
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_message_user._SLOT
     *
     * @param slot the value for miaosha_message_user._SLOT
     *
     * @mbg.generated
     */
    public void setSlot(String slot) {
        this.slot = slot == null ? null : slot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_message_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", messageid=").append(messageid);
        sb.append(", goodid=").append(goodid);
        sb.append(", orderid=").append(orderid);
        sb.append(", slot=").append(slot);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}