package com.seckill.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MiaoshaGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.GOODS_ID
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.MIAOSHA_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal miaoshaPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.STOCK_COUNT
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.START_DATE
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.END_DATE
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods._SLOT
     *
     * @mbg.generated
     */
    private String slot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.ID
     *
     * @return the value of miaosha_goods.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.ID
     *
     * @param id the value for miaosha_goods.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.GOODS_ID
     *
     * @return the value of miaosha_goods.GOODS_ID
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.GOODS_ID
     *
     * @param goodsId the value for miaosha_goods.GOODS_ID
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.MIAOSHA_PRICE
     *
     * @return the value of miaosha_goods.MIAOSHA_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getMiaoshaPrice() {
        return miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.MIAOSHA_PRICE
     *
     * @param miaoshaPrice the value for miaosha_goods.MIAOSHA_PRICE
     *
     * @mbg.generated
     */
    public void setMiaoshaPrice(BigDecimal miaoshaPrice) {
        this.miaoshaPrice = miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.STOCK_COUNT
     *
     * @return the value of miaosha_goods.STOCK_COUNT
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.STOCK_COUNT
     *
     * @param stockCount the value for miaosha_goods.STOCK_COUNT
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.START_DATE
     *
     * @return the value of miaosha_goods.START_DATE
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.START_DATE
     *
     * @param startDate the value for miaosha_goods.START_DATE
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.END_DATE
     *
     * @return the value of miaosha_goods.END_DATE
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.END_DATE
     *
     * @param endDate the value for miaosha_goods.END_DATE
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods._SLOT
     *
     * @return the value of miaosha_goods._SLOT
     *
     * @mbg.generated
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods._SLOT
     *
     * @param slot the value for miaosha_goods._SLOT
     *
     * @mbg.generated
     */
    public void setSlot(String slot) {
        this.slot = slot == null ? null : slot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", miaoshaPrice=").append(miaoshaPrice);
        sb.append(", stockCount=").append(stockCount);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", slot=").append(slot);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}